### ISSUE TITLE
Wrong GitHub link on the header

### ISSUE THREAD

**Issue by woswos** [joannakl/ossd_s20#10]
The GitHub link on the header is pointing to last year's GitHub repository.

<img width="1792" alt="Screen Shot 2020-02-01 at 4 59 49 PM" src="https://user-images.githubusercontent.com/10498874/73599730-aea60600-4514-11ea-9f22-827ca614447b.png">

I couldn't find the right file to edit to fix this issue. PR #6 seems to be fixing this issue but I am not sure. So, someone who knows how to fix this link, please fix it!

**Comment by joannakl** [comment]
Thanks. Good catch and suggestion for which PR fixes it.
