### ISSUE TITLE
Daily posts, change link title "LinkedIn" to the speaker's name

### ISSUE THREAD

**Issue by nedjulius** [joannakl/ossd_s20#12]
In the daily post for February 10th, two of the speakers have their names as link titles and the third mentioned speaker's link title says LinkedIn. I suggest changing it to his name (Christos Bacharakis).
![Screenshot 2020-02-12 at 00 10 47](https://user-images.githubusercontent.com/45975811/74304919-5fd64880-4d2c-11ea-900e-9c595b08689c.png)

**Comment by joannakl** [comment]
@nedjulius Thanks for reporting this. The Linkedin link should not have been there in the first place. I just fixed it in the latest commit at https://github.com/joannakl/ossd_s20/commit/6ba5ac834c46bcbe764bb624cc768cfdd6a877d5
